### PR TITLE
Create question about datasets

### PR DESCRIPTION
**Pull request by jinghaiD**
question about datasets

### CODE REVIEW

**Comment by zhlstone** [comment]
Can you privide the dataset  used in data.py line 50  [hkl_path = os.path.splitext(path)[0] + ".pkl"]

**Comment by zhlstone** [comment]
你还有在做这部分工作么

**Comment by zhlstone** [comment]
你还在继续做这部分工作么

**Comment by zhlstone** [comment]
> question about datasets

你还在做这部分工作么

**Comment by guoyage** [comment]
Hello, I tried to run your code, but found that the. pkl ending dataset is missing. 
Can you share this dataset or tell me how to get it.

**Comment by li-wenzhan** [comment]
> Hello, I tried to run your code, but found that the. pkl ending dataset is missing. Can you share this dataset or tell me how to get it.

I also found this problem and sincerely look forward to the author's reply.  Q_Q

**Comment by yuzhTHU** [comment]
It seems can be solved by change data.py. Change
```
hkl_path = os.path.splitext(path)[0] + ".pkl"
with open(hkl_path, 'rb') as handle:
    new_fet = pickle.load(handle, encoding='bytes')
fet_map[hkl_path] = torch.from_numpy(new_fet)
```
to
```
hkl_path = os.path.splitext(path)[0] + ".txt"
with open(hkl_path, 'r') as f:
    lines = f.readlines()
    mat = [[float(num) for num in line.split('\t')] for line in lines]
    new_fet = np.array(mat)
fet_map[hkl_path] = torch.from_numpy(new_fet)
```

However, there still exists bug in `model.py` when running `python train.py`, and I guess maybe that's because the variables' values in `constants.py` not match with the .txt data set.

**Comment by zhenfish** [comment]
Hello

> It seems can be solved by change data.py. Change
> 
> ```
> hkl_path = os.path.splitext(path)[0] + ".pkl"
> with open(hkl_path, 'rb') as handle:
>     new_fet = pickle.load(handle, encoding='bytes')
> fet_map[hkl_path] = torch.from_numpy(new_fet)
> ```
> 
> to
> 
> ```
> hkl_path = os.path.splitext(path)[0] + ".txt"
> with open(hkl_path, 'r') as f:
>     lines = f.readlines()
>     mat = [[float(num) for num in line.split('\t')] for line in lines]
>     new_fet = np.array(mat)
> fet_map[hkl_path] = torch.from_numpy(new_fet)
> ```
> 
> However, there still exists bug in `model.py` when running `python train.py`, and I guess maybe that's because the variables' values in `constants.py` not match with the .txt data set.

Hello!I solved the previous error this way, but the following error still occurs: vgg = vgg.view(-1, self.D)RuntimeError: shape '[-1, 512]' is invalid for input of size 59352. How can I solve it?

**Pull request merged**
